[feishu]
app_id = "cli_aaf7f6684178dd21"
app_secret = "Vt9LoPF69ShxAzYBDeEqRhUSjwn0vnmh"
app_token = "BYfEbGifrauvBDsArtSccYQqnPg"
table_id = "tbl3MQdtXmoJHwAr"
config_table_id = "tbl0SuteTNP5Y518"

[crawl]
request_interval = 0.5
max_per_school = 0

[auth]
enabled = false
password = "dR3mB0x_2024!"

[backend]
url = "http://localhost:8000"
